set expected_output \
  [multi_line \
    ".*" \
    "  --mcpu=ESPCHIP     Specify the name of the Xtensa configuration" \
    "		     \\\('esp8266', 'esp32', 'esp32s2', 'esp32s3' etc\\\)" \
    "		     Default is xtensa from the original GDB\." \
    ".*" \
  ]

eval "spawn $GDB $INTERNAL_GDBFLAGS $GDBFLAGS --help"
expect {
    -re $expected_output	{
	pass "mcpu option in help"
    }
    timeout 		{ fail "(timeout) get help" }
}

close
